version: '3'
services:
  deployment:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - '8080:8080'
    volumes:
      - .:/smarter-lite
      - /smarter-lite/node_modules
    command: npm run start
